### ISSUE TITLE
README.md file needed

### ISSUE THREAD

**Issue by tbertels** [tg-2/sacengine#1]
It would make this project much easier to find to mention that it's for the Sacrifice game from Shiny Entertainment.

And the build help info from [the discord channel](https://discord.com/channels/412626511246393345/761995528039825448):

Building sacengine from scratch:
Set up some D compiler, ideally LDC, version 1.23 is known to work:
https://github.com/ldc-developers/ldc/releases/tag/v1.23.0

$ git clone https://github.com/tg-2/sacengine
cd sacengine
$ git submodule init
$ git submodule update
$ dub build -b release-debug

If you simply extract the binary release, there are some build scripts for linux already in the repository, on Windows the following command might work:

./ldc2-1.23.0-windows-x64/bin/dub.exe build -b release-debug --compiler=./ldc2-1.23.0-windows-x64/bin/ldc2.exe

To run the engine, symlink your maps and data folder into the sacengine directory, check settings.txt for additional options.

On windows, you may need the following additional DLLs:
https://openal.org/downloads/

**Comment by tg-2** [comment]
Fixed by pull request #1. Thanks!
