### ISSUE TITLE
Add supported media list (Regular/Retail/etc CD, Steam, GOG, etc.) before setting up sacengine until 2024 or next decades

### ISSUE THREAD

**Issue by jkun-stargus-sc1gus-2020s** [tg-2/sacengine#6]
@tg-2 @fluffels @tbertels @RkShaRkz 
New to sacengine, plus new to Sacrifice on Windows10 since WindowsXP to Windows7 in 2007 to 2010s long ago.
I tried the CD version instead of Steam and GOG versions (That I don't do) for testing Sacrifice on W10, but sadly, it crashes because my 7/8yo AW17R2 laptop uses a NVIDIA card causing to crash and BSOD-crash to lag probably. :(
Will it be nice to add a list of supported media to work on installing and setting up Sacengine manually.

If not, here;
https://www.pcgamingwiki.com/wiki/Sacrifice#Availability
1. Compact Disc (Original/Regular, Retail, etc.)
2. Steam (MP Key not provided)
3. GOG (DRM free)
4. Sacrifice with All Patches (1, 2, 3, etc.)
5. Widescreen Mod-Patch-Thingy? (If works on either CD, Steam or GOG releases)

Hope that small list might serves any of us including everyone who have played Sacrifice here as well. ;)
Thanks in advance!

sidenote;
I might recommend installing Sacrifice on VMware with either Windows2000 or XP installed there, then IF sacengine doesn't be released to the public this year before the next decades even.

edit/update:
Added a few extra things to the post if tg(-1)/tg-2 might be inactive, active or not, we'll see.
I'll be waiting slower better than faster for it then. :\

**Comment by tg-2** [comment]
I am not sure what the concern is precisely.

- What is crashing? Sacrifice or sacengine?
- The widescreen patch for Sacrifice is unrelated to sacengine.
- You are commenting on a repository that is publicly available and has the current sacengine source code.

Anyway, any patch 3 install of Sacrifice will work. This is not really the place for technical support on Sacrifice, but you can join our discord: https://discord.com/invite/uTJgCEf

**Comment by jkun-stargus-sc1gus-2020s** [comment]
> I am not sure what the concern is precisely.
> 
>     * What is crashing? Sacrifice or sacengine?

Here;
- What is Crashing: Sacrifice, not sacengine
- BSOD (Blue Screen of Death or RCSOD (Randomly-colored Screen of Death) Crashes: Yes = some like a couple of less (SOD) crashes
- Desktop/Laptop Computer: Alienware 17 R2, bought in 2016 ago
- WindowsXP Installed: No
- WindowsVista Installed: No
- Windows7 Installed: No
- Windows8 Installed: No
- Windows10 Installed: Yes
- Windows11 Installed: No
- NVidia (Devices, Drivers, Software, etc) Installed: Yes = NVIDIA GeForce GTX 970M, NVIDIA Virtual Audio Device (Wave Extensible) (WDM), etc.
- Primary Display Driver: Direct3D HAL or Direct3D T&L HAL, which ever
- NV Profile Inspector (REQUIRED?) Downloaded, Installed & Used to Play Sacrifice (In-Game): Yes = Came with Sacrifice Profile for Nvidia (Profile Inspector) Drivers
- Installed with CD Version (Retail or Other) at Home: Yes
- Installed with/on GOGdotCom: No
- Installed with/on Steam: No
- SacEngine Installed: No
- Patch 3 or Patch 3.1 Installed: Yes, after CD Version of Sacrifice installed
- dgVoodoo2 (Wrapper, others, etc.) Installed: Yes
- dinputto8 Used/Installed: Yes
- VMware (Windows2000 or WinXP) Installed/Used: No, might recommended for Sacrifice without sacengine in future hopefully, idk :\
- Sacrifice (Widescreen) FOV Fix Installed after downloading [it](https://community.pcgamingwiki.com/files/file/1465-sacrifice-fov-fix/): Yes, after Patch 3.1 installed
- And that's it.

Hope that list of things could help.

>     * You are commenting on a repository that is publicly available and has the current sacengine source code.
>
> Anyway, any patch 3 install of Sacrifice will work. This is not really the place for technical support on Sacrifice.

sidenote:
Just letting you know that I can't write too much due to poor communication and poor text-writing along with feedback with keyboard-type-writing here for it seems.
Hope You and I might understand it not being [the place](https://github.com/tg-2/sacengine) for technical support for the game in future hopefully.

**Comment by tg-2** [comment]
Well, there are a lot of tips for how to configure win10 so Sacrifice works on the discord server I linked. The invite link is also in the README.
